# -*- coding: utf-8 -*-
"""asl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txpf-MqA3t70yTLGJVgkWnmlsYuG5xZa
"""

import kagglehub
import json


# Download latest version
path = kagglehub.dataset_download("ayuraj/asl-dataset")

print("Path to dataset files:", path)

import pandas as pd
import os
import kagglehub

from pathlib import Path
# 1. Download the dataset (returns a string path)
downloaded_path = kagglehub.dataset_download("ayuraj/asl-dataset")

# 2. Convert the string to a Path object
pathl = Path(downloaded_path)

print("Path to dataset files:", pathl)

for item in pathl.iterdir():
    if item.is_file():
        print(f"File: {item.name}")
    elif item.is_dir():
        print(f"Directory: {item.name}")

# The base path from your previous output
base_path = Path("/kaggle/input/asl-dataset")

# Point to the actual data folder
data_path = base_path / "asl_dataset"

print(f"Checking contents of: {data_path}")

# Now list the contents of the internal folder
for item in data_path.iterdir():
    if item.is_dir():
        # This will likely show folders for each character (a, b, c...)
        print(f"Label Folder: {item.name}")
    else:
        print(f"File: {item.name}")

data_list = []
# Supported image extensions
valid_extensions = {'.jpg', '.jpeg', '.png', '.bmp'}

# rglob("*") searches every subfolder recursively
for image_path in data_path.rglob("*"):
    if image_path.suffix.lower() in valid_extensions:
        data_list.append({
            "path": str(image_path),
            "label": image_path.parent.name  # Takes the name of the folder the image is in
        })

# Create the DataFrame
df = pd.DataFrame(data_list)

# Shuffle for randomness
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Total images found across all folders: {len(df)}")
print(df.head(10))

import matplotlib.pyplot as plt
from PIL import Image
import random

# Pick a random index from your dataframe
random_index = random.randint(0, len(df) - 1)

# Get path and label
img_path = df.iloc[random_index]['path']
label = df.iloc[random_index]['label']

# Open and display
img = Image.open(img_path)
plt.imshow(img)
plt.title(f"Label: {label}")
plt.axis('off') # Hide the x and y axis numbers
plt.show()

from sklearn.model_selection import train_test_split

# We split the DataFrame itself
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,     # Ensures you get the same split every time you run it
    stratify=df['label'] # Crucial: ensures both sets have the same % of each letter
)

print(f"Training samples: {len(train_df)}")
print(f"Testing samples: {len(test_df)}")

"""## Model Building"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Define image dimensions and batch size
IMG_HEIGHT = 64
IMG_WIDTH = 64
BATCH_SIZE = 200

# Create an ImageDataGenerator for training with augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,          # Normalize pixel values to [0, 1]
    rotation_range=15,       # Rotate images by a random degree
    width_shift_range=0.1,   # Shift image horizontally
    height_shift_range=0.1,  # Shift image vertically
    shear_range=0.1,         # Apply shearing transformations
    zoom_range=0.1,          # Apply random zoom
    horizontal_flip=False,   # Do not flip horizontally for ASL signs as it changes meaning
    fill_mode='nearest'      # Fill newly created pixels after rotation/shift
)

# Create an ImageDataGenerator for validation/testing (only rescaling)
test_datagen = ImageDataGenerator(rescale=1./255)

# Get the number of unique classes (labels)
num_classes = df['label'].nunique()
print(f"Number of classes: {num_classes}")

# Create data generators from the DataFrames
train_generator = train_datagen.flow_from_dataframe(
    train_df,                 # Your training dataframe
    x_col='path',             # Column containing image paths
    y_col='label',            # Column containing labels
    target_size=(IMG_WIDTH, IMG_HEIGHT), # Resize images to this size
    batch_size=BATCH_SIZE,
    class_mode='categorical', # Use 'categorical' for one-hot encoded labels
    seed=42
)

validation_generator = test_datagen.flow_from_dataframe(
    test_df,                  # Your testing dataframe
    x_col='path',             # Column containing image paths
    y_col='label',            # Column containing labels
    target_size=(IMG_WIDTH, IMG_HEIGHT), # Resize images to this size
    batch_size=BATCH_SIZE,
    class_mode='categorical', # Use 'categorical' for one-hot encoded labels
    seed=42
)

# Define the CNN model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_WIDTH, IMG_HEIGHT, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(256, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5), # Add dropout for regularization
    Dense(num_classes, activation='softmax') # Output layer with num_classes neurons and softmax activation
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Display model summary
model.summary()

# Save class indices
class_indices = train_generator.class_indices
# class_indices is a dict mapping class name to index. We map index to class name.
index_to_class = {str(v): k for k, v in class_indices.items()}
with open('class_indices.json', 'w') as f:
    json.dump(index_to_class, f)
print("Class indices saved successfully as class_indices.json!")

"""## Model Training
Now, we'll train the Convolutional Neural Network (CNN) model using the `train_generator` and validate it with the `validation_generator`. We'll set the number of epochs and steps per epoch.
"""

# Train the model
EPOCHS = 50 # You can adjust this number

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // BATCH_SIZE
)

"""## Training History Visualization
It's crucial to visualize the training history to understand how well the model learned and to detect potential issues like overfitting. We'll plot the accuracy and loss for both the training and validation sets over the epochs.
"""

import matplotlib.pyplot as plt

# Plot training and validation accuracy
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

# Plot training and validation loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""## Save and Load Model

To use the trained model later without retraining, you should save it. Keras models can be saved using `model.save()` in various formats. The `.keras` format is the recommended native Keras format, but HDF5 (`.h5`) is also common.
"""

model.save('asl_cnn_model.h5')
print("Model saved successfully as asl_cnn_model.h5!")

from google.colab import files
try:
    files.download("asl_cnn_model.h5")
    files.download("class_indices.json")
except Exception as e:
    print(f"Colab download failed (probably because you are not in colab): {e}")